# Usa una imagen base oficial de Python
FROM python:3.10-slim

# Establece un directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY ../requirements.txt ./
COPY ../.env ./

ENV FLASK_APP=main.py
ENV FLASK_ENV=development


# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación al contenedor
COPY ../ .

# Exponer el puerto que la aplicación usará
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["flask", "--app", "main.py", "run", "--host=0.0.0.0", "--port=5000"]


